version: "3"

services:
  pg_data:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgresql
      POSTGRES_PASSWORD: password
      POSTGRES_DBA: postgresql
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    volumes:
      - redis_data:/var/lib/redis
    ports:
      - "6379:6379"


volumes:
  db_data: {}
  redis_data: {}