server:
  port: 8088

spring:
  application:
    name: MS-25 Project

  jpa:
    database: postgresql
    generate-ddl: true
    hibernate:
      ddl-auto: validate
    show-sql: true

  datasource:
    password: password
    username: postgresql
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgresql
  liquibase:
    enabled: ${LIQUIBASE_ENABLED:true}
#    change-log: db/changelog/

